# Generated by Django 3.1.1 on 2020-11-19 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField(choices=[('S', 'Singles'), ('D', 'Doubles'), ('MD', 'Mixed Doubles')])),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='game_type_preference',
            field=models.IntegerField(choices=[('S', 'Singles'), ('D', 'Doubles'), ('MD', 'Mixed Doubles')], default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_created_by', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_match', to='match.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='match',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
