# Generated by Django 3.1.1 on 2020-11-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20201119_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='game_type_preference',
        ),
        migrations.AddField(
            model_name='customuser',
            name='doubles',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='mixed_doubles',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='singles',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
