# Generated by Django 3.1.1 on 2020-11-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20201121_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
