# Generated by Django 3.1.1 on 2020-11-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
