# Generated by Django 3.1.1 on 2020-11-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_message_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
